version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  app:
    build:
      context: .
      target: base
    volumes:
      - ./src:/opt/app-root/src
    command: >
      sh -c "uvicorn main:app --host=0.0.0.0 --port 8000 --reload"
    ports:
      - "8080:8000"
    depends_on:
      - db
