"""change problem, add answer table

Revision ID: 74a4a90205df
Revises: 302601498ddd
Create Date: 2023-08-30 22:45:24.719083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a4a90205df'
down_revision: Union[str, None] = '302601498ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=30), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.add_column('problem', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('subjective_answer', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'subjective_answer')
    op.drop_column('problem', 'explanation')
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
